In [29]:
import numpy
MAZE_L = 50
MAZE_W = 50
MAZE_H = 50
# 使用nd-array模拟作为点云数据
a = 1
point_cloud = numpy.ones([MAZE_L, MAZE_W, MAZE_H], dtype=int)

In [30]:
import random
# 挖掘范围点
action_point = []
for i in range(MAZE_L):
    for j in range(MAZE_W):
        action_point.append([i,j])
point = random.randint(0,len(action_point))


In [36]:
action = 1
action_l = action % 20 - 1
action_w = action // 20
print(action_w,action_l)

0 0


In [38]:
import numpy as np
s = np.ones([3,3,3],dtype=int)
s_ = np.expand_dims(s, axis=0)
print(s_)


[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
