## 下面是CEM的测试集

In [ ]:
import numpy as np


task_depth = 6
# 设定cell大小
m, n = 5, 5
cell_grid_map = np.random.randint(0,5,(m,n))
print(cell_grid_map)
index = np.argmax(cell_grid_map)
x = int(index / n)
y = index % n

# 挖掘动作空间
action_space_approach = [1,0,0]
action_space_dig = [0,1,0]
action_space_dump = [0,0,1]
action_list_cem = []

while cell_grid_map[x,y] > task_depth:
    cell_grid_map[x,y] = task_depth
    action_list_cem.append(action_space_approach)
    action_list_cem.append(action_space_dig)
    action_list_cem.append(action_space_dump)
    index = np.argmax(cell_grid_map)
    x = int(index / n)
    y = index % n  
print(cell_grid_map) 
print(action_list_cem)



[[0 2 3 1 2]
 [2 3 3 2 0]
 [0 2 3 0 0]
 [4 3 1 0 4]
 [1 2 1 4 2]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1]]
