# 对numpy矩阵的保存和读取

In [19]:
import numpy as np

# 点云地图点数
point_size = 800
# 训练集大小 暂设 100
train_size = 100
# 最低深度
min_depth = -5 
# 最高深度
max_depth = 10
np_save = np.ones((train_size,point_size,point_size))
for i in range(0,train_size):
    # 生成随机地图
    np_save[i,:,:] = np.random.randint(min_depth, max_depth, (point_size,point_size))

np.save("test_x",np_save)
goal = [
    [0,0],[0,50],[50,0],[50,50],
    [4]
    ]
goal1 = [
    [0,0],[0,2],[2,0],[2,2],
    [4]
]

### 另一种保存的方式
j = np.array([1, 5, 8])
k = np.array([11, 31, 9])
l = np.array([67, 40, 23])
 用默认key值
np.savez("arr3",  j, k, l)
 要写出完整的文件名，包括后缀
arr3 = np.load("arr3.npz")
print(arr3.files)
print(arr3["arr_0"])


## 读取

In [20]:
train_x = np.load("test_x.npy")
print(train_x.shape)

(100, 800, 800)


## 参数设置 

In [8]:
# 任务深度
task_depth = -4
# 单元格 长和宽
cell_x = 5
cell_y = 5
# tile 索引
index_x = 0
index_y = 0


In [9]:
tile_space = np.zeros((train_size,point_size,point_size))
for i in range(0,train_size):
    
tile_space = np.where(np_random > task_depth,1,0)
# np.sum(tile_space[0:cell_x,0:cell_y])
tile_grid = np.zeros([20,20],dtype = int)

# 将tile_grid按照一定规则转换
for i in range(0,len(tile_grid)):
    for j in range(0,len(tile_grid[0])):
        tile_grid[i,j] = 1 if np.sum(tile_space[i * cell_x:i * cell_x + cell_x,j * cell_y:j*cell_y+cell_y]) > 0 else 0 
print(tile_grid)


[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [10]:
# 输出动作 [挖掘，上，下，左，右]
action_space_exc = [1,0,0,0,0]
action_space_up = [0,1,0,0,0]
action_space_down = [0,0,1,0,0]
action_space_left = [0,0,0,1,0]
action_space_right = [0,0,0,0,1]
action_list = []
direct_bool = True
index_x = 0
index_y = 0
length_x = len(tile_grid)
length_y = len(tile_grid[0])

# TEM测试集
while index_x < len(tile_grid) and index_y < len(tile_grid[0]):
    if tile_grid[index_x,index_y] != 0:
        action_list.append(action_space_exc)
    if direct_bool:
        if index_x < length_y - 1:
            action_list.append(action_space_right)
            index_x = index_x + 1
        else:
            action_list.append(action_space_down)
            index_y = index_y + 1
            direct_bool = bool(1-direct_bool)
    else:
        if index_x > 0:
            action_list.append(action_space_left)
            index_x = index_x - 1
        else:
            action_list.append(action_space_down)
            index_y = index_y + 1
            direct_bool = bool(1-direct_bool)
print(action_list)

[[1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 

## 下面是CEM的测试集

In [11]:
import numpy as np
# 设定cell大小
m, n = 5, 5
cell_grid_map = np.random.randint(0,5,(m,n))
print(cell_grid_map)
index = np.argmax(cell_grid_map)
x = int(index / n)
y = index % n

# 挖掘动作空间
action_space_approach = [1,0,0]
action_space_dig = [0,1,0]
action_space_dump = [0,0,1]
action_list_cem = []

while cell_grid_map[x,y] > task_depth:
    cell_grid_map[x,y] = task_depth
    action_list_cem.append(action_space_approach)
    action_list_cem.append(action_space_dig)
    action_list_cem.append(action_space_dump)
    index = np.argmax(cell_grid_map)
    x = int(index / n)
    y = index % n  
print(cell_grid_map) 
print(action_list_cem)



[[1 1 2 2 3]
 [1 1 4 3 2]
 [1 4 1 3 0]
 [3 0 4 0 4]
 [0 1 4 0 1]]
[[-4 -4 -4 -4 -4]
 [-4 -4 -4 -4 -4]
 [-4 -4 -4 -4 -4]
 [-4 -4 -4 -4 -4]
 [-4 -4 -4 -4 -4]]
[[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1]]
