# 对numpy矩阵的保存和读取

In [2]:
import numpy as np

# 点云地图点数
point_size = 160
# 训练集大小 暂设 10000
train_size = 10000
# 最低深度
min_depth = -5 
# 最高深度
max_depth = 10
np_save = np.ones((train_size,point_size,point_size),dtype = int)
for i in range(0,train_size):
    # 生成随机地图
    np_save[i,:,:] = np.random.randint(min_depth, max_depth, (point_size,point_size))

# np.save("test_x",np_save)
goal = [
    [0,0],[0,50],[50,0],[50,50],
    [4]
    ]
goal1 = [
    [0,0],[0,2],[2,0],[2,2],
    [4]
]

### 另一种保存的方式
j = np.array([1, 5, 8])
k = np.array([11, 31, 9])
l = np.array([67, 40, 23])
 用默认key值
np.savez("arr3",  j, k, l)
 要写出完整的文件名，包括后缀
arr3 = np.load("arr3.npz")
print(arr3.files)
print(arr3["arr_0"])


## 读取

In [3]:
train_x = np.load("test_x.npy")
print(train_x.shape)

(10000, 32, 32)


## 参数设置 
生成（10000，32，32）的tile_map(训练集)

In [4]:
import numpy as np

# 任务深度
task_depth = 6
# 单元格 长和宽
cell_x = 5
cell_y = 5
# tile 索引
index_x = 0
index_y = 0
# 将实际地图信息转化为0，1二进制信息
tile_space = np.where(np_save > task_depth,1,0)
# np.sum(tile_space[0:cell_x,0:cell_y])
tile_grid = np.zeros([train_size ,int(point_size/cell_x),int(point_size/cell_y)],dtype = int)
summ = 0
# 将tile_grid按照一定规则转换
for t in range(0,train_size):
    for i in range(0,len(tile_grid[0])):
        for j in range(0,len(tile_grid[1])):
            tile_grid[t,i,j] = 1 if np.sum(tile_space[t,i * cell_x:i * cell_x + cell_x,j * cell_y:j*cell_y+cell_y]) > 0 else 0 
            if tile_grid[t,i,j] == 0:
                summ = summ + 1
np.save("test_x",tile_grid)
print(summ)

38697


## TEM的label

In [5]:
# 输出动作 [挖掘，上，下，左，右]
import copy


action_space_exc = [1,0,0,0,0]
action_space_up = [0,1,0,0,0]
action_space_down = [0,0,1,0,0]
action_space_left = [0,0,0,1,0]
action_space_right = [0,0,0,0,1]
action_list_space = []

length_x = len(tile_grid[0])
length_y = len(tile_grid[1])

# TEM测试集
for i in range(0,train_size):
    index_x = 0
    index_y = 0
    action_list = []
    direct_bool = True
    while index_x < len(tile_grid[0]) and index_y < len(tile_grid[1]):
        if tile_grid[i,index_x,index_y] != 0:
            action_list.append(action_space_exc)
        if direct_bool:
            if index_x < length_y - 1:
                action_list.append(action_space_right)
                index_x = index_x + 1
            else:
                action_list.append(action_space_down)
                index_y = index_y + 1
                direct_bool = bool(1-direct_bool)
        else:
            if index_x > 0:
                action_list.append(action_space_left)
                index_x = index_x - 1
            else:
                action_list.append(action_space_down)
                index_y = index_y + 1
                direct_bool = bool(1-direct_bool)
    action_list_space.append(copy.deepcopy(action_list))


In [6]:
# 输出动作 [挖掘，上，下，左，右]
import copy
import numpy as np

action_space_exc = 1
action_space_up = 2
action_space_down = 3
action_space_left = 4
action_space_right = 5

# 读取tile_grid
tile_grid = np.load('test_x.npy')
# 下一个动作标签
action_list_space = []
# 历史动作
history_action_list = []
chopped_map = tile_grid[0].copy()
#建立一个numpy shape(n,32,32)
chopped_map1 = np.ones((20000,32,32),dtype=int)
# TEM测试集
index_chop = 0
length_x = len(chopped_map)
length_y = len(chopped_map[0])
for i in range(0,train_size):
    index_x = 0
    index_y = 0
    action_list = []
    direct_bool = True
    while index_x < len(chopped_map) and index_y < len(chopped_map[0]):
        if chopped_map[index_x,index_y] != 0:
            # 追加历史动作
            history_action_list.append(action_list[:])
            # 将动作加入动作标签
            action_list_space.append(action_space_exc)
            # 将地图加入chopped
            chopped_map1[index_chop] = chopped_map
            index_chop = index_chop + 1
            # 将此坐标点化为 0
            chopped_map[index_x,index_y] = 0
            action_list.append(action_space_exc)
            

        if direct_bool:
            if index_x < length_y - 1:
                # 追加历史动作
                history_action_list.append(action_list[:])
                # 将动作加入动作标签
                action_list_space.append(action_space_right)
                # 将地图加入chopped
                chopped_map1[index_chop] = chopped_map
                index_chop = index_chop + 1

                action_list.append(action_space_right)
                index_x = index_x + 1
            else:
                # 追加历史动作
                history_action_list.append(action_list[:])
                # 将动作加入动作标签
                action_list_space.append(action_space_down)
                # 将地图加入chopped
                chopped_map1[index_chop] = chopped_map
                index_chop = index_chop + 1

                action_list.append(action_space_down)
                index_y = index_y + 1
                direct_bool = bool(1-direct_bool)
        else:
            if index_x > 0:

                # 追加历史动作
                history_action_list.append(action_list[:])
                # 将动作加入动作标签
                action_list_space.append(action_space_left)
                # 将地图加入chopped
                chopped_map1[index_chop] = chopped_map
                index_chop = index_chop + 1

                action_list.append(action_space_left)
                index_x = index_x - 1
            else:

                # 追加历史动作
                history_action_list.append(action_list[:])
                # 将动作加入动作标签
                action_list_space.append(action_space_down)
                # 将地图加入chopped
                chopped_map1[index_chop] = chopped_map
                index_chop = index_chop + 1

                action_list.append(action_space_down)
                index_y = index_y + 1
                direct_bool = bool(1-direct_bool)
    break
print(len(history_action_list))
print(chopped_map.shape)
print(chopped_map1.shape)
# print(history_action_list)
for i in range(len(history_action_list)):
    history_action_list[i] = history_action_list[i][-8:]
    if len(history_action_list[i]) < 8:
        history_action_list[i] = (8 - len(history_action_list[i])) * [0] + history_action_list[i]
    
# print(action_list_space)
print(history_action_list[:5])
# print(chopped_map[:5])



2044
(32, 32)
(20000, 32, 32)
[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 1, 5], [0, 0, 0, 0, 0, 1, 5, 1], [0, 0, 0, 0, 1, 5, 1, 5]]


In [7]:
import torch
import torch.nn as nn
import torch.utils.data as Data
import torchvision      # 数据库模块
import matplotlib.pyplot as plt


class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Sequential(  # input shape (1, 32, 32)
            nn.Conv2d(
                in_channels=1,      # input height
                out_channels=16,    # n_filters
                kernel_size=3,      # filter size
                stride=1,           # filter movement/step
                padding=1,      # 如果想要 con2d 出来的图片长宽没有变化, padding=(kernel_size-1)/2 当 stride=1
            ),      # output shape (16, 28, 28)
            nn.ReLU(),    # activation
            nn.MaxPool2d(kernel_size=2),    # 在 2x2 空间里向下采样, output shape (16, 14, 14)
        )
        self.conv2 = nn.Sequential(  # input shape (16, 14, 14)
            nn.Conv2d(16, 32, 3, 1, 1),  # output shape (32, 14, 14)
            nn.ReLU(),  # activation
            nn.MaxPool2d(kernel_size=2),  # output shape (32, 7, 7)
        )
        self.out1 = nn.Linear(2056, 128)   # fully connected layer, output 10 classes
        self.out = nn.Linear(128, 128)
        self.test = nn.Linear(128,5)

    def forward(self, x,y):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)   # 展平多维的卷积图成 (batch_size, 32 * 7 * 7)
        #拼接步骤
        
        # print(x.shape)
        # print(y.shape)
        x = torch.cat([x,y],1)
        # print(x.shape)
        output = self.out1(x)
        output = self.out(output)
        output = self.test(output)

        return x



In [8]:

EPOCH = 1000
LR = 0.001          # 学习率

cnn = CNN()

optimizer = torch.optim.Adam(cnn.parameters(), lr=LR)   # optimize all cnn parameters
loss_func = nn.CrossEntropyLoss()   # the target label is not one-hotted

s_ = np.expand_dims(chopped_map1[:2040], axis=1)
torch_data = torch.Tensor(s_)

# print(cnn(torch_data))

b_y = torch.LongTensor(history_action_list)

test_y = torch.LongTensor(action_list_space)
print(test_y.shape)
for epoch in range(EPOCH):
    for step in range(0,2040,5):   # 分配 batch data, normalize x when iterate train_loader
        output = cnn(torch_data[step:step+5],b_y[step:step+5])               # cnn output
        loss = loss_func(output, test_y[step:step+5])   # cross entropy loss
        optimizer.zero_grad()           # clear gradients for this training step
        loss.backward()                 # backpropagation, compute gradients
        optimizer.step()                # apply gradients


torch.Size([2044])


In [ ]:
from symbol import term

index_re = 20
test_output = cnn(torch_data[:index_re],b_y[:index_re])
print(test_output)
# 输出一维最大值 纵坐标
pred_y = torch.max(test_output, 1)[1].data.numpy().squeeze()
print(pred_y, 'prediction number')
print(test_y[:index_re].numpy())

tensor([[34.2182, 34.2089, 34.2089,  ...,  0.0000,  0.0000,  0.0000],
        [34.4879, 34.2089, 34.2089,  ...,  0.0000,  0.0000,  1.0000],
        [34.4879, 34.2089, 34.2089,  ...,  0.0000,  1.0000,  5.0000],
        ...,
        [34.5047, 34.2089, 34.2089,  ...,  1.0000,  5.0000,  1.0000],
        [34.5047, 34.2089, 34.2089,  ...,  5.0000,  1.0000,  5.0000],
        [34.5047, 34.2089, 34.2089,  ...,  1.0000,  5.0000,  1.0000]],
       grad_fn=<CatBackward0>)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] prediction number
[1 5 1 5 1 5 1 5 1 5 1 5 1 5 1 5 1 5 1 5]
