In [3]:
import numpy as np

print(round(np.sin(30 * np.pi / 180),1))
space_now = np.zeros([2, 2, 2], dtype=int)
a = [1,1,1]
space_now[1,1,1]=1
print(space_now)

0.5
[[[0 0]
  [0 0]]

 [[0 0]
  [0 1]]]


In [3]:

print(np.arccos(250/252.6) * 180 / np.pi)

8.227745515207078


In [4]:
import numpy as np
def math_a(angle):
    return angle * np.pi / 180
for base_angle in range (180):
    index_x = np.sin(math_a(base_angle))
    index_y = np.cos(math_a(base_angle))
    print(index_x,index_y)

0.0 1.0
0.01745240643728351 0.9998476951563913
0.03489949670250097 0.9993908270190958
0.05233595624294383 0.9986295347545738
0.0697564737441253 0.9975640502598242
0.08715574274765817 0.9961946980917455
0.10452846326765346 0.9945218953682733
0.12186934340514748 0.992546151641322
0.13917310096006544 0.9902680687415704
0.15643446504023087 0.9876883405951378
0.17364817766693033 0.984807753012208
0.1908089953765448 0.981627183447664
0.20791169081775931 0.9781476007338057
0.224951054343865 0.9743700647852352
0.24192189559966773 0.9702957262759965
0.25881904510252074 0.9659258262890683
0.27563735581699916 0.9612616959383189
0.29237170472273677 0.9563047559630354
0.3090169943749474 0.9510565162951535
0.32556815445715664 0.9455185755993168
0.3420201433256687 0.9396926207859084
0.35836794954530027 0.9335804264972017
0.374606593415912 0.9271838545667874
0.3907311284892737 0.9205048534524404
0.40673664307580015 0.9135454576426009
0.42261826174069944 0.9063077870366499
0.43837114678907746 0.8987940

In [7]:
space_now = np.zeros([1, 2, 2], dtype=int)
print(space_now)
space_now[-1,-1,-1] = 1
print(space_now)

[[[0 0]
  [0 0]]]
[[[0 0]
  [0 1]]]


In [14]:
print(np.concatenate((np.array([1,1]),[1])))

[1 1 1]
